### ISSUE TITLE
Cartographer with ROS2 and camera D435

### ISSUE THREAD

**Issue by ninamwa** [intel/ros2_intel_realsense#110]
Hi. I want to use Cartographer together with my D435 camera and ROS Eloquent. 
I have been trying to use this tutorial (https://intel.github.io/robot_devkit_doc/pages/rs_slam.html)  but get some problems as I do not have the T265 camera. What I have done is to comment out the T265 node, and also change the tracking_frame from "camera_pose_optical_frame" to "base_link" as the first one is related to the T265 camera. 

By watching the tf-tree, I can see that a lot of frames are not connected. 

[frames.pdf](https://github.com/intel/ros2_intel_realsense/files/4184696/frames.pdf)
(even though the T265 node is commented out, the static transform between T265 and D435 is still published, thats why it is in the tf-tree). 
What can be seen is that there lacks a connection from odom_frame to the rest and also from the D435 link. 
Am I supposed to change "odom_frame" in the code with "odom", and the camera links in the turtlebot URDF with the D435 camera? This would might connect the whole tree, but seems like a lot of changes in the code. From the tutorial, I got the impression that I could just run the commands and that it would be straight forward without changing the code too much, but now I am unsure. 

Have anyone tried to do the same and could help me out a bit? 
Thank you!

**Comment by ahuizxc** [comment]
hi

> Hi. I want to use Cartographer together with my D435 camera and ROS Eloquent.
> I have been trying to use this tutorial (https://intel.github.io/robot_devkit_doc/pages/rs_slam.html) but get some problems as I do not have the T265 camera. What I have done is to comment out the T265 node, and also change the tracking_frame from "camera_pose_optical_frame" to "base_link" as the first one is related to the T265 camera.
> 
> By watching the tf-tree, I can see that a lot of frames are not connected.
> 
> [frames.pdf](https://github.com/intel/ros2_intel_realsense/files/4184696/frames.pdf)
> (even though the T265 node is commented out, the static transform between T265 and D435 is still published, thats why it is in the tf-tree).
> What can be seen is that there lacks a connection from odom_frame to the rest and also from the D435 link.
> Am I supposed to change "odom_frame" in the code with "odom", and the camera links in the turtlebot URDF with the D435 camera? This would might connect the whole tree, but seems like a lot of changes in the code. From the tutorial, I got the impression that I could just run the commands and that it would be straight forward without changing the code too much, but now I am unsure.
> 
> Have anyone tried to do the same and could help me out a bit?
> Thank you!

hi, our tutorial is just for d435 and t265 and the parameters is tuned for these devices, like we drop the odomtry information from turtlebot and use t265's odomtry information, so it may have some difficuties if you only using d435. So I if you are using turtlebot, you can refer to the turtlebot's tutorial. Thanks.
