### ISSUE TITLE
colcon build --symlink-install with error

### ISSUE THREAD

**Issue by Schloern93** [intel/ros2_intel_realsense#162]
Hello,
I'm trying to get the new intel Real Sense Tracking Camera T265 running. I have tried to build the provided package according to the manual. 
I get the following error message in the terminal. It is attached to the message. Ask for help.
I used Ubuntu 18.04 and installed ros-dashing-desktop.

Thanks and best regards 
Florian

[Error Msg.txt](https://github.com/intel/ros2_intel_realsense/files/5263084/Error.Msg.txt)

**Comment by shunta3296** [comment]
Hello,
I have the exact same problem.
The errors are the same and the environment is the same.
Have you found a solution to this problem?

**Comment by Schloern93** [comment]
Hey,

Yeah i found a way which works. Just Remind me on Soneday. Im not at home for a few days


Von: shunta3296
Gesendet: Freitag, 30. Oktober 2020 10:53
An: intel/ros2_intel_realsense
Cc: Schloern93; Author
Betreff: Re: [intel/ros2_intel_realsense] colcon build --symlink-install with error (#162)

Hello,
I have the exact same problem.
The errors are the same and the environment is the same.
Have you found a solution to this problem?

**Comment by ShuntaIto-keio** [comment]
Hi,

I'm really glad to get your reply.
Japan is now on Sunday. Is it Sunday in your country already?
Please let me know how you solved that problem.

**Comment by AndreaEirale** [comment]
Hi everybody! 
I am experiencing the exact same error! Can you please let me know how you solved the problems?
Thank you very much!

**Comment by Schloern93** [comment]
Hallo,
I have updated my system to ros eloquent. And switched to the current project from intel: 
https://github.com/IntelRealSense/realsense-ros

**Comment by Schloern93** [comment]
I close this issue now.
