### ISSUE TITLE
How to use multiple camera?

### ISSUE THREAD

**Issue by revizes** [intel/ros2_intel_realsense#43]
according to https://realsense.intel.com/how-to-multiple-camera-setup-with-ros ,
for using multiple camera, i should use ros not ros2.

is there way to use multiple camera on ros2?

Thank you.

**Comment by xhuan28** [comment]
ROS2 package doesn't support multiple cameras currently. But we are planning to do this in the near future. Stay tuned.

**Comment by revizes** [comment]
thx for reply.

can you tell me what component will be used for distinguishing between cameras?
