### ISSUE TITLE
Not supported on Mac

### ISSUE THREAD

**Issue by bobgates** [intel/ros2_intel_realsense#47]
Now that the main RealSense library is getting more mature on Mac, can we get the ros2 library also running on Mac? Specifically, the 2.21 version of librealsense supports the T265 on the Mac - how about on Ros2 on the Mac?

**Comment by ahuizxc** [comment]
> Now that the main RealSense library is getting more mature on Mac, can we get the ros2 library also running on Mac? Specifically, the 2.21 version of librealsense supports the T265 on the Mac - how about on Ros2 on the Mac?

Hi OSX support is still ongoing, we will inform you as soon as it's done! thanks:)

**Comment by ahuizxc** [comment]
> Now that the main RealSense library is getting more mature on Mac, can we get the ros2 library also running on Mac? Specifically, the 2.21 version of librealsense supports the T265 on the Mac - how about on Ros2 on the Mac?

Hi bob, due to cv_bridge has some dependency problems, so currently this wrapper does not support MacOS, thanks
