### ISSUE TITLE
port aligned depth images from intel-ros/realsense

### ISSUE THREAD

**Issue by yechun1** [intel/ros2_intel_realsense#8]
@dorodnic @sharronliu 
We are developing [ros2_object_analytics](https://github.com/intel/ros2_object_analytics) which use [intel/ros2_intel_realsense](https://github.com/intel/ros2_intel_realsense) as dependence.We require a feature "publish aligned depth images" from realsense package. As we checked [intel-ros/realsense 2.0.2](https://github.com/intel-ros/realsense/tree/2.0.2) had already supported publishing aligned frames feature. But ros2_intel_realsense not merged that code, it just ported based on https://github.com/intel-ros/realsense/tree/2.0.1, and have no any updates. May I ask if you have any plan to port latest intel-ros/realsense code to ros2_intel_realsense?  

For immediate usage, I could also contribute on porting 2.0.2 to enable aligned depth images from realsense to ros2 realsense. Do you have any suggestion? Thanks.

**Comment by sharronliu** [comment]
It will be great to keep enabling v2.0.2 features in ROS2. Yet not started due to my bandwidth unavailable in short while. Contribution is welcomed anytime :).

**Comment by sharronliu** [comment]
https://github.com/intel/ros2_intel_realsense/pull/11
