### ISSUE TITLE
View IMU data of D435i in ROS2

### ISSUE THREAD

**Issue by yahoo2016** [intel/ros2_intel_realsense#90]
I just got a D435i, all camera displays are fine in Rviz.  How can I check IMU under ROS2?

**Comment by ahuizxc** [comment]
@yahoo2016 HI Rviz2 can't display either imu or accel message, so you can get these data from " ros2 topic echo".

**Comment by yahoo2016** [comment]
I found out I need to patch Linux kernel to have D435i fully functional on Nvidia Jetsons.  I was able to use realsence-viewer to display imu data.  I'll try " ros2 topic echo".
